algoritmo "Aula 04 a"
var
   a, b, c: Inteiro

inicio
      Escreva("Digite um valor para A: ")
      Leia(a)
      Escreva("Digite um valor para B: ")
      Leia(b)
      Escreva("Digite um valor para C: ")
      Leia(c)

      Escreval("A =", a, " | B =", b, " | C =", c, ".")
      Escreval("A > B? ", a > b)
      Escreval("A < C? ", a < c)
      Escreval("C >= B? ", c <= b)
      Escreval("C <= A? ", c <= a)
      Escreval("B = A? ", b = a)
      Escreval("A <> C? ", a <> c)
fimalgoritmo
